# Generated by Django 5.0.7 on 2024-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilevo",
            name="import_href",
            field=models.URLField(blank=True, unique=True),
        ),
    ]
